### ISSUE TITLE
Feature: User can 

### ISSUE THREAD

**Issue by Logisticx** [Logisticx/ajax-project#2]
## ⚙️Motivation
User will be able to view items in the cosmetic store for Fortnite from previous weeks.

## 📐 Functionality

Create a responsive page that displays an image with a title, icon and description for how much an item costs, with a button that contains interactive icons to transition the image carousel.

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/103016667/173640083-9d17d01a-d585-4a0d-9e6d-2bf0477b51db.png)
![image](https://user-images.githubusercontent.com/103016667/173640113-32d000b4-8113-43a2-9e9b-e7d811a70620.png)

## ✅ Task List

> #####

- [ ] Add a div[data-view="previous-items"] to the HTML
- [ ] add a header that indicates the page is for the items from previous weeks, with an indication of which week it is from.
- [ ] Create an empty UL in the HTML, and fill it with "dummy data"
  - [ ] After contents in UL is formatted correctly, create a function to create the contents in the UL as a DOM Tree, and append it to the UL of the "previous-items" parent.
  - [ ] Remove "dummy HTML data"
-[ ] Add a button with clickable arrows.
  - [ ] After the button is "clicked" to go "next" (right arrow), display left arrow
  - [ ] After button is clicked, week number and images will change according to conditions of: Items from week #.
- [ ] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [ ]  Test all functionality again in a private browsing session.
- [ ] Fix all errors.
