### ISSUE TITLE
User can search for a specific item

### ISSUE THREAD

**Issue by Logisticx** [Logisticx/ajax-project#3]
## ⚙️ Feature
User will be able to search for a specific Item.

## 📐 Functionality

Search bar with a submit button will display a modal of the searched item, display an image with the name, icon and cost of the item. A header showing the name and the last time that item was in the store. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://user-images.githubusercontent.com/103016667/173644448-867e4bb2-23e5-4af2-926e-e1ea25ba81a9.png)
![image](https://user-images.githubusercontent.com/103016667/173645791-c60d6044-1fda-43f1-973f-e328a7e11f55.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Add a div[data-view="search-items"] to the HTML
- [ ] add a header that says "Looking for an Item?"
- [ ] Create a modal to be displayed when the search button is clicked.
  - [ ] When the modal is opened, display a header with the item name, last in store week date, and an image with an icon and the cost.
  -[ ] add a way to cancel out of the modal, either a click that is not any of the modal elements, or include an [ x ] button.
- [ ] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [ ]  Test all functionality again in a private browsing session.
- [ ] Fix all errors.
