### ISSUE TITLE
User can press a button to bring up a random item

### ISSUE THREAD

**Issue by Logisticx** [Logisticx/ajax-project#4]
## ⚙️Motivation
User can display a random item from the database, and be shown image name, last date in store, and cost.

## 📐 Functionality
Button will display a modal to display a random item from the database and include it's name, last date in store, and cost.

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/103016667/173657692-0b577e10-c94e-419d-acb5-4bb195ec5e88.png)
![image](https://user-images.githubusercontent.com/103016667/173657732-18ed9064-ebae-46c5-a8f2-7eaca3da16de.png)

## ✅ Task List
- [ ] Create a button that will display a modal.
  - [ ] When the modal is opened, display a header with the item name, last in store week date, and an image with an icon and the cost.
  -[ ] Add a way to cancel out of the modal, either a click that is not any of the modal elements, or include an [ x ] button.
- [ ] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [ ] Test all functionality again in a private browsing session.
- [ ] Fix all errors.
