### ISSUE TITLE
User can view all items

### ISSUE THREAD

**Issue by Logisticx** [Logisticx/ajax-project#5]
## ⚙️ Feature
User will be able to view the whole database of items in the store.

## 📐 Functionality
A page containing all of the items in the store, in alphabetical order. 

## 🖼️ Wireframes
![image](https://user-images.githubusercontent.com/103016667/173658302-c4beb4c6-f9d1-4d21-9cf1-d6ebed12265b.png)
![image](https://user-images.githubusercontent.com/103016667/173658339-8c82e2a9-9bbb-453b-ae0c-809eff4a403a.png)

## ✅ Task List
- [ ] Add a div[data-view="all-items"] to the HTML
- [ ] Add a header that says "All Items"
- [ ] Add a button with clickable arrows.
  - [ ] After the button is "clicked" to go "next" (right arrow), display left arrow
  - [ ] After button is clicked, page # and images will transition to the next "page", displaying more.
- [ ] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [ ] Test all functionality again in a private browsing session.
- [ ] Fix all errors.
